sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedramadan/react-docker-aws:latest -f Dockerfile.dev .
script:
  - docker run ahmedramadan/react-docker-aws:latest npm run test -- --coverage
